
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h4>Import LC List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered ">
                <thead>
                    <tr>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-1">{{ $langs['lcdate'] }}</th>
                        <th class="col-md-1">{{ $langs['shipmentdate'] }}</th>
                        <th class="col-md-2">{{ $langs['buyer_id'] }}</th>
                        <th class="col-md-1">{{ $langs['country_id'] }}</th>
                        <th class="col-md-2 text-right">{{ $langs['lcamount'] }}</th>
                        <th class="col-md-1">{{ $langs['currency_id'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
                <?php $lcimport=DB::table('acc_lcimports')->where('com_id',$com_id)->get();  ?>
                @foreach($lcimport as $item)
                <?php 
				$currency=DB::table('acc_currencies')->where('id',$item->currency_id)->first(); 
				$currency_name=''; isset($currency) && $currency->id >0 ?  $currency_name=$currency->name : $currency_name ='';
				
				$country=DB::table('acc_countries')->where('id',$item->country_id)->first(); 
				$country_name=''; isset($country) && $country->id >0 ?  $country_name=$country->name : $country_name ='';
				
				$supplier=DB::table('acc_suppliers')->where('id',$item->currency_id)->first(); 
				$supplier_name=''; isset($supplier) && $supplier->id >0 ?  $supplier_name=$supplier->name : $supplier_name =''; ?>
                {{-- */$x++;/* --}}
                <tr>
                        <td class="col-md-2">{{ $item->lcnumber }}</td>
                        <td class="col-md-1">{{ $item->lcdate }}</td>
                        <td class="col-md-1">{{ $item->shipmentdate }}</td>
                        <td class="col-md-2">{{ $supplier_name }}</td>
                        <td class="col-md-1">{{ $country_name }}</td>
                        <td class="col-md-2 text-right">{{ $item->lcvalue }}</td>
                        <td class="col-md-1">{{ $currency_name }}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Import->Lc info</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>

