        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h4>Order List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered ">
                <thead>
                    <tr>
                        <th class="col-md-3">{{ $langs['ordernumber'] }}</th>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-2">{{ $langs['ordervalue'] }}</th>
                        <th class="col-md-2">{{ $langs['orderqty'] }}</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
					Session::has('com_id') ? 
					$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
					$order=DB::table('acc_orderinfos')->where('com_id',$com_id)->get(); 
				?>
				{{-- */$x=0;/* --}}
                @foreach($order as $item)
                <?php
					$lc=DB::table('acc_lcinfos')->where('id',$item->lcnumber)->first(); 
					$lc_number=''; isset($lc) && $lc->id >0 ?  $lc_number=$lc->lcnumber : $lc_number ='';
					
					$unit=DB::table('acc_units')->where('id',$item->unit_id)->first(); 
					$unit_name=''; isset($unit) && $unit->id >0 ?  $unit_name=$unit->name : $unit_name ='';

					$currency=DB::table('acc_currencies')->where('id',$item->currency_id)->first(); 
					$currency_name=''; isset($currency) && $currency->id >0 ?  $currency_name=$currency->name : $currency_name ='';
				
				?>
                {{-- */$x++;/* --}}
                <tr>
                        <td>{{ $item->ordernumber }}</td>
                        <td>{{ $lc_number }}</td>
                        <td>{{ $item->ordervalue . '('. $currency_name .')'}}</td>
                        <td>{{ $item->orderqty . '('. $unit_name .')'}}}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Order</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
