@extends('app')

@section('htmlheader_title', 'Buyer')

@section('contentheader_title', 'Buyer')

@section('main-content')

 <div class="container">
 <div class="box" >
    <div class="table-responsive">
        <div class="box-header">
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
			// data collection filter method by session	
			$data=array('lc_id'=>'','ord_id'=>'','dfrom'=>'0000-00-00','dto'=>'0000-00-00');

			Session::has('orlc_id') ? 
			$data=array('lc_id'=>Session::get('orlc_id')) : 
			$data=array('lc_id'=>''); 
		

			
			if (isset($data['lc_id']) && $data['lc_id']>0):
				$lc=DB::table('acc_lcinfos')->where('com_id',$com_id)->where('id',$data['lc_id'])->first();
				$lc_number=''; isset($lc) && $lc->id>0 ? $lc_number=$lc->lcnumber : $lc_number='';
				$cur_id=''; isset($lc) && $lc->id>0 ? $cur_id=$lc->currency_id : $cur_id='';
			// for single account
			echo '<tr><td ><h3 class="pull-left">Process Cost</h3></td>
				<td class="text-right" ><h3 aling="right">'.$lc_number.'</h3><h5 ></h5></td></tr>';
			else:
				// for multiple account
				echo '<tr><td class="text-center" colspan="2"><h4>LC-wise Order List</h4><h5 ></h5></td></tr>';
			endif;
		?>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered ">
                <thead>

                <tr><td colspan="9"><a href="{!! url('/orderinfo/report?flag=filter') !!}"> Filter  </a>
					<?php 
                    	$flags=''; isset($_GET['flag']) ? $flags=$_GET['flag'] : ''; 
						 !isset($data['lc_id']) ? $data['lc_id']='' : '' ;
                   
				    // to get data by fileter
					?>
                    @if ($flags=='filter')
                           {!! Form::open(['url' => 'orderinfo/orfilter', 'class' => 'form-horizontal']) !!}
            
                            <div class="form-group">
                                {!! Form::label('lc_id', $langs['lc_id'], ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-6"> 
                                    {!! Form::select('lc_id', $lcinfos, null, ['class' => 'form-control select2','id'=>'lc_id']) !!}
                                </div>    
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-3">
                                {!! Form::submit($langs['find'], ['class' => 'btn btn-primary form-control']) !!}
                                </div>    
                            </div>
                          {!! Form::close() !!}
                     @endif
               </td></tr>
                    <tr>
                        <th class="col-md-1">{{ $langs['sl'] }}</th>
                        <th class="col-md-3">{{ $langs['ordernumber'] }}</th>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-2">{{ $langs['ordervalue'] }}</th>
                        <th class="col-md-2">{{ $langs['orderqty'] }}</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
					if (isset($data['lc_id']) && $data['lc_id']!=''):
						$order=DB::table('acc_orderinfos')->where('com_id',$com_id)->where('lcnumber',$data['lc_id'])->get();
					endif;
				?>
				{{-- */$x=0;/* --}}
                @foreach($order as $item)
                <?php 
				DB::table('acc_ocms1')->first();
					$unit=DB::table('acc_units')->where('id',$item->unit_id)->first();
					$unit_name=''; isset($unit) && $unit->id > 0 ? $unit_name=$unit->name : $unit_name='';

					$currency=DB::table('acc_currencies')->where('id',$cur_id)->first();
					$currency_name=''; isset($currency) && $currency->id > 0 ? $currency_name=$currency->name : $currency_name='';
				?>
                {{-- */$x++;/* --}}
                <tr>
                        <td width="50">{{ $x }}</td>
                        <td>{{ $item->ordernumber }}</td>
                        <td>{{ $lcnumber }}</td>
                        <td>{{ $item->ordervalue . '('. $currency_name .')'}}</td>
                        <td>{{ $item->orderqty . '('. $unit_name .')'}}}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Order</td><td class="text-right">Report generated by: </td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
@endsection
