@extends('print')


@section('main-content')

        <div class="box-header">
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h4>Export LC List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered ">
                <thead>
                    <tr>
                        <th class="col-md-1">{{ $langs['sl'] }}</th>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-1">{{ $langs['lcdate'] }}</th>
                        <th class="col-md-1">{{ $langs['shipmentdate'] }}</th>
                        <th class="col-md-2">{{ $langs['buyer_id'] }}</th>
                        <th class="col-md-1">{{ $langs['country_id'] }}</th>
                        <th class="col-md-2 text-right">{{ $langs['lcamount'] }}</th>
                        <th class="col-md-1">{{ $langs['currency_id'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
                @foreach($lcinfo as $item)
                {{-- */$x++;/* --}}
                <tr>
                        <td class="col-md-1">{{ $x }}</td>
                        <td class="col-md-2">{{ $item->lcnumber }}</td>
                        <td class="col-md-1">{{ $item->lcdate }}</td>
                        <td class="col-md-1">{{ $item->shipmentdate }}</td>
                        <td class="col-md-2">{{ $item->buyer->name }}</td>
                        <td class="col-md-1">{{ $item->country->name }}</td>
                        <td class="col-md-2 text-right">{{ $item->lcamount }}</td>
                        <td class="col-md-1">{{ $item->currency->name }}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Lc info</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
@endsection
