 <div class="container">
 <div class="box" >
    <div class="table-responsive">
        <div class="box-header">
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h5>Export LC List</h5></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-1">{{ $langs['lcdate'] }}</th>
                        <th class="col-md-1">{{ $langs['shipmentdate'] }}</th>
                        <th class="col-md-2">{{ $langs['buyer_id'] }}</th>
                        <th class="col-md-1">{{ $langs['country_id'] }}</th>
                        <th class="col-md-2 text-right">{{ $langs['lcamount'] }}</th>
                        <th class="col-md-1">{{ $langs['currency_id'] }}</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
					Session::has('com_id') ? 
					$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
					$lcinfo=DB::table('acc_lcinfos')->where('com_id',$com_id)->get(); 
				?>
				{{-- */$x=0;/* --}}
                @foreach($lcinfo as $item)
                <?php
					$country=DB::table('acc_countries')->where('id',$item->country_id)->first(); 
					$country_name=''; isset($country) && $country->id >0 ?  $country_name=$country->name : $country_name ='';
					
					$buyer=DB::table('acc_buyerinfos')->where('id',$item->buyer_id)->first(); 
					$buyer_name=''; isset($buyer) && $buyer->id >0 ?  $buyer_name=$buyer->name : $buyer_name ='';

					$currency=DB::table('acc_currencies')->where('id',$item->buyer_id)->first(); 
					$currency_name=''; isset($currency) && $currency->id >0 ?  $currency_name=$currency->name : $currency_name ='';
				
				?>

                {{-- */$x++;/* --}}
                <tr>
                        <td class="col-md-2">{{ $item->lcnumber }}</td>
                        <td class="col-md-1">{{ $item->lcdate }}</td>
                        <td class="col-md-1">{{ $item->shipmentdate }}</td>
                        <td class="col-md-2">{{ $buyer_name }}</td>
                        <td class="col-md-1">{{ $country_name }}</td>
                        <td class="col-md-2 text-right">{{ $item->lcamount }}</td>
                        <td class="col-md-1">{{ $currency_name }}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Lc info</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>

