        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h1 align="center">'.$com_name.'</h1></td></tr>';
		?>
        <tr><td class="text-center"><h4>Outlet List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="col-md-3">{{ $langs['name'] }}</th>
                        <th class="col-md-2">{{ $langs['emp_id'] }}</th>
                        <th class="col-md-2">{{ $langs['address'] }}</th>
                        <th class="col-md-2">{{ $langs['email'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
                <?php $employee=array(''=>'Select ...', '1'=>'Hasan Habib'); 
					  $outlets=DB::table('acc_outlets')->where('com_id',$com_id)->get(); ?>
                @foreach($outlets as $item)
                {{-- */$x++;/* --}}
                <tr>
                        <td>{{ $item->name }}</td>
                        <td>{{ $employee[$item->emp_id] }}</td>
                        <td>{{ $item->address }}</td>
                        <td>{{ $item->email }}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Sales->Outlet</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
