@extends('print')

@section('htmlheader_title', 'Orderinfos')

@section('contentheader_title', 'Order information')

@section('main-content')

 <div class="container">
 <div class="box" >
    <div class="table-responsive">
        <div class="box-header">
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h4>Style List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="style-table" class="table table-bordered">
                <thead>
                    <tr>
                        <th>{{ $langs['sl'] }}</th>
                        <th>{{ $langs['name'] }}</th>
                        <th>{{ $langs['ordernumber'] }}</th>
                        <th>{{ $langs['stylevalue'] }}</th>
                        <th>{{ $langs['styleqty'] }}</th>
                        <th>{{ $langs['description'] }}</th>
                    </tr>
                </thead>
                <tbody>
                <?php  ?>
                {{-- */$x=0;/* --}}
                @foreach($styles as $item)
                 <?php 
					$unit=DB::table('acc_units')->where('id',$item->unit_id)->first(); 
					$unit_name=''; isset($unit) && $unit->id > 0 ? $unit_name=$unit->name: $unit_name='';

				 	$order = DB::table('acc_orderinfos')->where('id',$item->ordernumber)->first();
					$ordernumber=''; isset($order) && $order->id > 0 ? $ordernumber=$order->ordernumber: $ordernumber='';
					$currency_id=''; isset($order) && $order->id > 0 ? $currency_id=$order->currency_id: $currency_id='';
					
					$currency=DB::table('acc_currencies')->where('id',$currency_id)->first(); 
					$currency_name=''; isset($currency) && $currency->id > 0 ? $currency_name=$unit->name: $currency_name='';
					
				   ?>
                    {{-- */$x++;/* --}}
                    <tr>
                        <td width="50">{{ $x }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $ordernumber }}</td>
                        <td>{{ $item->stylevalue .' ('. $currency_name.')' }}</td>
                        <td>{{ $item->styleqty .' ('. $unit_name.')' }}</td>
                        <td>{{ $item->description }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Sales->Style</td><td class="text-right">Report generated by: {{ $item->user_id }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
@endsection
