@extends('print')

@section('htmlheader_title', 'Buyer')

@section('contentheader_title', 'Buyer')

@section('main-content')

 <div class="container">
 <div class="box" >
    <div class="table-responsive">
        <div class="box-header">
        <table class="table borderless">
        <?php 
			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h2 align="center">'.$com_name.'</h2></td></tr>';
		?>
        <tr><td class="text-center"><h4>Order List</h4></td></tr>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered ">
                <thead>
                    <tr>
                        <th class="col-md-1">{{ $langs['sl'] }}</th>
                        <th class="col-md-3">{{ $langs['ordernumber'] }}</th>
                        <th class="col-md-2">{{ $langs['lcnumber'] }}</th>
                        <th class="col-md-2">{{ $langs['ordervalue'] }}</th>
                        <th class="col-md-2">{{ $langs['orderqty'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
                @foreach($order as $item)
                {{-- */$x++;/* --}}
                <tr>
                        <td width="50">{{ $x }}</td>
                        <td>{{ $item->ordernumber }}</td>
                        <td>{{ $item->lc->lcnumber }}</td>
                        <td>{{ $item->ordervalue . '('. $item->lc->currency->name .')'}}</td>
                        <td>{{ $item->orderqty . '('. $item->unit->name .')'}}}</td>
                 </tr>
                @endforeach

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Order</td><td class="text-right">Report generated by: {{ $item->user->name }}</td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
@endsection
