@extends('app')

@section('htmlheader_title', 'Client Ledger')

@section('contentheader_title', 	  ' Client Ledger')
@section('main-content')

<style>
    table.borderless td,table.borderless th{
     border: none !important;
	}

	h1{
		font-size: 1.6em;
	}
	h5{
		font-size: 1.2em; margin:0px
	}
	#unit {width: 10px} 
	#cur {width: 10px}
</style>

 <div class="container">
 <div class="box" >
 <div class="box" >
         <div class="box-header">
        <a href="{{ url('invenmaster/client_print') }}" title="{{ $langs['print'] }}" class="btn btn-primary pull-right btn-sm trash-btn"><i class="fa fa-print"></i></a>
	 </div><!-- /.box-header -->

    <div class="table-responsive">
        <table  width="100%>
        </table>

            <table id="buyerinfo-table" class="table table-bordered table-striped">
                <thead>
                <tr><td colspan="7"><a href="{!! url('/invenmaster/client?flag=filter') !!}"> Filter  </a>
					<?php 
                    	$flags=''; isset($_GET['flag']) ? $flags=$_GET['flag'] : ''; 
						 !isset($data['prod_id']) ? $data['prod_id']='' : '' ;
                   
				    // to get data by fileter
					?>
                    @if ($flags=='filter')
                           {!! Form::open(['url' => 'invenmaster/clfilter', 'class' => 'form-horizontal']) !!}
            
                            <div class="form-group">
                                {!! Form::label('dto', $langs['dto'], ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-6"> 
                                    {!! Form::text('dto', date('Y-m-d'), ['class' => 'form-control', 'id'=>'dto','required']) !!}
                                </div>    
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-3">
                                {!! Form::submit($langs['find'], ['class' => 'btn btn-primary form-control']) !!}
                                </div>    
                            </div>
                          {!! Form::close() !!}
                     @endif
               </td></tr>
                    <tr>
                        <th class="col-md-1 text-center">{{ $langs['sl'] }}</th>
                        <th class="col-md-2">{{ $langs['idate'] }}</th>
                        <th class="col-md-1">{{ $langs['itype'] }}</th>
                        <th class="col-md-3">{{ $langs['note'] }}</th>
                        <th class="col-md-1 text-right" >{{ $langs['rcvd'] }}</th>
                        <th class="col-md-1 text-right" >{{ $langs['issue'] }}</th>
                        <th class="col-md-1 text-right" >{{ $langs['balance'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
                @foreach($sale as $item)
                         <tr>
                        	<td class="text-center">{{ $x }}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class=" text-right"></td>
                            <td class="text-right"></td>
                            <td class="text-right"></td>
                             </tr>
                @endforeach
                <tr><td colspan="4" class="text-right">Total</td><td class="text-right">{{ $ttl_rcvds }}</td><td class="text-right">{{ $ttl_issues }}</td><td class="text-right">{{ $balances }}</td></tr>

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Buyer</td><td class="text-right">Report generated by: </td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
@endsection

@section('custom-scripts')

<script type="text/javascript">
        
    jQuery(document).ready(function($) {        
        $(".trandetail").validate();
	    $( "#dto" ).datepicker({ dateFormat: "yy-mm-dd" }).val();
    });
        
</script>

@endsection
