@extends('app')

@section('htmlheader_title', 'Client Ledger')

@section('contentheader_title', 	  ' Client Ledger')
@section('main-content')

 <div class="container">
 <div class="box" >
 <div class="box" >
         <div class="box-header">
        <a href="{{ url('invenmaster/client_print') }}" title="{{ $langs['print'] }}" class="btn btn-primary pull-right btn-sm trash-btn"><i class="fa fa-print"></i></a>
	 </div><!-- /.box-header -->

    <div class="table-responsive">
        <table  width="100%>
        </table>

            <table id="buyerinfo-table" class="table table-bordered table-striped">
                <thead>
                <tr><td colspan="7"><a href="{!! url('/invenmaster/client?flag=filter') !!}"> Filter  </a>
					<?php 
                    	$flags=''; isset($_GET['flag']) ? $flags=$_GET['flag'] : ''; 
						 !isset($data['prod_id']) ? $data['prod_id']='' : '' ;
                   
				    // to get data by fileter
					?>
                    @if ($flags=='filter')
                           {!! Form::open(['url' => 'invenmaster/clfilter', 'class' => 'form-horizontal']) !!}
            
                            <div class="form-group">
                                {!! Form::label('dto', $langs['dto'], ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-6"> 
                                    {!! Form::text('dto', date('Y-m-d'), ['class' => 'form-control', 'id'=>'dto','required']) !!}
                                </div>    
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-3">
                                {!! Form::submit($langs['find'], ['class' => 'btn btn-primary form-control']) !!}
                                </div>    
                            </div>
                          {!! Form::close() !!}
                     @endif
               </td></tr>
                    <tr>
                        <th class="col-md-1 text-center">{{ $langs['sl'] }}</th>
                       	<th >{{ $langs['acc_id'] }}</th>
                        <th class="col-md-1 text-right" >{{ $langs['debit'] }}</th>
                        <th class="col-md-1 text-right" >{{ $langs['credit'] }}</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0; $debits=''; $credits=''; /* --}}
                @foreach($tran as $item)
                    {{-- */$x++;/* --}}
                		<?php 
						$debit=''; $credit='';
							$item->amount>0 ? $debit=$item->amount : $credit=substr($item->amount,1);
							$debits += $debit;
							$credits += $credit;
						?>
                         <tr>
                        	<td class="text-center">{{ $x }}</td>
                            <td>{{ $acccoa[$item->acc_id] }}</td>
                            <td class="text-right">{{ $debit>0 ? number_format($debit) : '' }}</td>
                            <td class="text-right">{{ $credit>0 ? number_format($credit) : '' }}</td>
                             </tr>
                @endforeach
                <tr><td  class="text-right">Total</td><td class="text-right"></td><td class="text-right">{{ $debits }}</td><td class="text-right">{{ $credits }}</td></tr>

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Export->Buyer</td><td class="text-right">Report generated by: </td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
@endsection

@section('custom-scripts')

<script type="text/javascript">
        
    jQuery(document).ready(function($) {        
        $(".trandetail").validate();
	    $( "#dto" ).datepicker({ dateFormat: "yy-mm-dd" }).val();
    });
        
</script>

@endsection
