
        <table class="table borderless">
        <?php 
			// data collection filter method by session	
			$data=array('pro_id'=>'');

			Session::has('pro_id') ? 
			$data=array('pro_id'=>Session::get('pro_id')) : ''; 

			Session::has('com_id') ? 
			$com_id=Session::get('com_id') : $com_id='' ;// echo $com_id.'osama';
			$com=DB::table('acc_companies')->where('id',$com_id)->first(); $com_name=''; 
			isset($com) && $com->id>0 ? $com_name=$com->name : $com_name=''; 
			echo '<tr><td colspan="2"><h1 align="center" style="margin:0px">'.$com_name.'</h1></td></tr>
			<tr><td colspan="2"><h4 align="center" style="margin:0px">Project Planning Report</h4></td></tr>';
			
		?>
        </table>
        </div><!-- /.box-header -->

            <table id="buyerinfo-table" class="table table-bordered">
                <thead>
                    <tr>
                        <th class="col-md-1 text-center">{{ $langs['sl'] }}			</th>
                        <th class="col-md-2">{{ $langs['segment'] }}		</th>
                        <th class="col-md-3">{{ $langs['stdate'] }}		</th>
                        <th class="col-md-3 ">{{ $langs['cldate'] }}	</th>
                        <th class="col-md-1 ">{{ $langs['bamount'] }}	</th>
                    </tr>
                </thead>
                <tbody>
				{{-- */$x=0;/* --}}
				<?php
                	Session::has('pro_id') ? 
					$project=DB::table('acc_projects')->where('com_id',$com_id)->where('id',$data['pro_id'])->get()	:'';
				?>
				@foreach($project as $item)
				<?php 
					$pplanning=DB::table('acc_pplannings')->where('pro_id',$item->id)->where('group_id',0)->get();
				?>
                	<tr><td colspan="5">{{$item->name }}</td></tr>
                        @foreach($pplanning as $item)
                        {{-- */$x++;/* --}}
                        <tr>
                                <td width="50" class="text-center">{{ $x }}</td>
                                <td style="padding-left:30px">{{ $item->segment }}	</td>
                                <td>{{ $item->stdate }}</td>
                                <td>{{ $item->cldate }}	</td>
                                <td>{{ $item->bamount }}	</td>
                         </tr>
							<?php 
                                $pplanning=DB::table('acc_pplannings')->where('group_id',$item->id)->where('pro_id', $item->pro_id)->get();
                            ?>
                                    @foreach($pplanning as $item)
                                    {{-- */$x++;/* --}}
                                    <tr>
                                            <td width="50" class="text-center">{{ $x }}</td>
                                            <td style="padding-left:60px">{{ $item->segment }}	</td>
                                            <td>{{ $item->stdate }}</td>
                                            <td>{{ $item->cldate }}	</td>
                                            <td>{{ $item->bamount }}	</td>
                                     </tr>
                                    @endforeach 
                        @endforeach 
                @endforeach 
                        <tr><td colspan="3" class="text-right"></td><td class="text-right"></td></tr>             

                </tbody>
            </table>
			<div class="box-header">
                <table class="table borderless">
                <tr><td class="text-left">Source: Project->Report</td><td class="text-right">Report generated by: </td></tr>
                </table>
            </div><!-- /.box-header -->
        </div>
     </div>
</div>
